# Generated by Django 5.0.7 on 2024-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_compras_productos_rename_estudiante_visitantes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('horarios', models.IntegerField()),
                ('profesion', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='edad',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='compras',
            old_name='telefono',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='domicilio',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='nombredeempresa',
        ),
    ]
